name: CD Main
on:
  push:
    branches:
      - main
jobs:
  publish-major-react-router-url:
    if: contains(github.event.head_commit.message, '[major]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Publish New Major Version
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          yarn
          yarn version --new-version major --message "react-router-url v%s"
          yarn build
          yarn publish
          git push
  publish-minor-react-router-url:
    if: contains(github.event.head_commit.message, '[minor]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Publish New Minor Version
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          yarn
          yarn version --new-version minor --message "react-router-url v%s"
          yarn build
          yarn publish
          git push  
  publish-patch-react-router-url:
    if: ${{!contains(github.event.head_commit.message, '[major]') && !contains(github.event.head_commit.message, '[minor]')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Publish New Patch Version
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          yarn
          yarn version --new-version patch --message "react-router-url v%s"
          yarn build
          yarn publish
          git push