name: CD Main
on:
  push:
    branches:
      - main
jobs:
  publish-major-react-hook-url:
    if: contains(github.event.head_commit.message, '[major]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@master
        id: changed-hook
        with:
          paths: react-hook-url
      - name: Use Node
        if: steps.changed-hook.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Publish New Major Version
        if: steps.changed-hook.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd react-hook-url
          yarn
          yarn version --new-version major --no-git-tag-version
          yarn publish
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          git add .
          git commit -m "New react-hook-url major version"
          git push
  publish-major-react-router-url:
    if: contains(github.event.head_commit.message, '[major]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@master
        id: changed-router
        with:
          paths: react-router-url
      - name: Use Node
        if: steps.changed-router.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Publish New Major Version
        if: steps.changed-router.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd react-router-url
          yarn
          yarn version --new-version major --no-git-tag-version
          yarn publish
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          git add .
          git commit -m "New react-router-url major version"
          git push
  publish-minor-react-hook-url:
    if: contains(github.event.head_commit.message, '[minor]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@master
        id: changed-hook
        with:
          paths: react-hook-url
      - name: Use Node
        if: steps.changed-hook.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Publish New Minor Version
        if: steps.changed-hook.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd react-hook-url
          yarn
          yarn version --new-version minor --no-git-tag-version
          yarn publish
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          git add .
          git commit -m "New react-hook-url minor version"
          git push
  publish-minor-react-router-url:
    if: contains(github.event.head_commit.message, '[minor]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@master
        id: changed-router
        with:
          paths: react-router-url
      - name: Use Node
        if: steps.changed-router.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Publish New Minor Version
        if: steps.changed-router.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd react-router-url
          yarn
          yarn version --new-version minor --no-git-tag-version
          yarn publish
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          git add .
          git commit -m "New react-router-url minor version"
          git push
  publish-patch-react-hook-url:
    if: ${{!contains(github.event.head_commit.message, '[major]') && !contains(github.event.head_commit.message, '[minor]')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@master
        id: changed-hook
        with:
          paths: react-hook-url
      - name: Use Node
        if: steps.changed-hook.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Publish New Patch Version
        if: steps.changed-hook.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd react-hook-url
          yarn
          yarn version --new-version patch --no-git-tag-version
          yarn publish
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          git add .
          git commit -m "New react-hook-url patch version"
          git push
  publish-patch-react-router-url:
    if: ${{!contains(github.event.head_commit.message, '[major]') && !contains(github.event.head_commit.message, '[minor]')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@master
        id: changed-router
        with:
          paths: react-router-url
      - name: Use Node
        if: steps.changed-router.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Publish New Patch Version
        if: steps.changed-router.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd react-router-url
          yarn
          yarn version --new-version patch --no-git-tag-version
          yarn publish
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          git add .
          git commit -m "New react-router-url patch version"
          git push
  rebase:
    needs: [
      publish-patch-react-hook-url,
      publish-patch-react-router-url,
      publish-minor-react-hook-url,
      publish-minor-react-router-url,
      publish-major-react-hook-url,
      publish-major-react-router-url]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v2
        with:
          ref: 'dev'
      - name: Rebase Dev
        run: |
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git pull origin main
          git rebase remotes/origin/main
          git push